### ISSUE TITLE
allow for fractional parameters

### ISSUE THREAD

**Issue by br3ttb** [mike-matera/FastPID#1]
I'm not sure if this is an issue for your target application, but oftentimes a parameter value of 1 is just too big.  older industrial pids (whose internals are all integer math) will often divide the parameter by a fixed value (and tell the user what that is).  So it might be /10 for P and D, /100 for I.  The user then enters a  P of 50 if they want 5.  This allows the user to have an effective P value of as low as 0.1, which can be helpful for aggressive processes.

**Comment by br3ttb** [comment]
...as a now see PARAM_MULT.  jesus. sorry.

**Comment by mike-matera** [comment]
Hi! 

Thank you so much for taking the time to look at my code. I have to make choices about bits when I do the multiplier. Right now the bits and shift give the coefficients a domain of: 

2 bits for the whole part and 23 for the fractional part so: [3, ~2.4-07]

I'm wondering if it would be better to do:

3 bits for the whole part and 22 for the fractional part so: [7, ~4.8-07]

What do you think? Right now the parameters are limited to 25 bits. I might be able to squeeze in one or two more bits. Maybe.

**Comment by br3ttb** [comment]
over the years I've toyed with the idea of doing an integer version of the
library,  and I've considered this issue. I've never been able to settle on
something beautiful.  also, frankly, it looks like you're far better with
bit-wise operations than I am.

What I can contribute is the following:  tuning parameters never need to be
better than 3 significant digits; I nearly always use 2.  There is no
valuable difference between 2.123 and 2.124. None. depending on the
situation you might need 121 or 0.123,  but you'll never need 121.123.

So, maybe you can infer your shift for each parameter when the parameter is
set? it might be a heavy operation, but you're not doing on-the-fly tuning
changes, so it shouldn't hurt too much.

**Comment by br3ttb** [comment]
If you're looking for a fixed range for all parameters, I think you want to
have more on the high side.  0.001 to 100 is probably enough. if you can do
1e-4 to 1e4 you'll get no (legitimate) complaints.

**Comment by mike-matera** [comment]
Thanks! I've updated the parameter domain. It's now [1023 to 6.103515625e-05]. It's not possible to change the domain on a per-constant basis because the whole pipeline depends on the same shift being applied to the calculations.
