### ISSUE TITLE
type conflict

### ISSUE THREAD

**Issue by SonSiont** [mike-matera/FastPID#17]
In line 53 of FastPID.h the variable _p is defined as uint32_t.
In line 88 of FastPID.cpp "P = int32_t(_p) * int32_t(err);" is used as signed int.
This is should not be an issue but maybe the definition should be fixed.

**Comment by mike-matera** [comment]
In general, that's a bad cast and should be expected to cause a bug. However, those are only set in `setCoefficients()` where the range is limited to `0 < param < PARAM_MAX`. So the cast will never cause a problem.
