### ISSUE TITLE
Hello my friend

### ISSUE THREAD

**Issue by SkyNet26** [mike-matera/FastPID#2]
Help with the FastPID library. When the feedback changes, the output changes between 0 and 1.

**Comment by mike-matera** [comment]
Can you provide example code?

**Comment by SkyNet26** [comment]
Please tell me why the library does not work, values do not increase more than 1.

**Comment by SkyNet26** [comment]
Thank you!

сб, 21 апр. 2018 г., 19:24 Mike Matera <notifications@github.com>:
