### ISSUE TITLE
Appying bit shift to possibly negative value.

### ISSUE THREAD

**Issue by TBAMax** [mike-matera/FastPID#20]
In the `step()` function in the end there is:
`  // Remove the integer scaling factor. `
 `int16_t rval = out >> PARAM_SHIFT;`
 out variable type here is: `int64_t out`
When applying shift to the negative integer, the sign bit gets shifted also and may mess up the result.
So when the limits are set to allow also for negative values, what happens? Or are only postitive values allowed, and I missed that? Seems to be no check done for that in the code to allow only positive values.

**Comment by mike-matera** [comment]
Hi! I think you're right! I can't believe I didn't test for this issue. Let me take a look and see if I can make a test and fix the bug.

**Comment by TBAMax** [comment]
Hi! It is possible that compiler already takes this into account, and there is no issue (this is most likely). I have been thinking about this meanwhile.

**Comment by mike-matera** [comment]
I wrote some new tests. According to the documentation doing this in C/C++ causes undefined behavior. It seems that on my x86-64 machine that behavior is an arithmetic shift that makes negative numbers come out okay. I don't have an easy way to test this on Arduino right now. Do you?
