### ISSUE TITLE
Use FastPID for cooling?

### ISSUE THREAD

**Issue by hossians** [mike-matera/FastPID#8]
Hi

I wonder how to use FastPID for cooling, i.e. you want the output to increase when the input increases? One way of doing it would be to use negative Kp,Ki and Kd. But the FastPID do not accept values below 0. By modifying the library I have done tests with negative values and works as intended, but I assume the check for negative values are there for a reason?

/Henrik

**Comment by mike-matera** [comment]
Simple! 

All you have to do is invert the feedback. 

output = myPID.step(-input) 

Cheers
./m
